### ISSUE TITLE
Infinite durability is broken & our way of fixing it will spam non harmfull errors in console

### ISSUE THREAD

**Issue by cloakfox** [UtechtDustin/Builder-s-Wand#74]
Current wands.yml: https://gist.github.com/cloakfox/7fba96d242d7db4e59565a9940626ea5
Errors spammed with our current fix for durability wands: https://gist.github.com/cloakfox/812b8032b7a25a0cfb6fc93a0aae960e

Proper infinite durability wands will straight up change to 25 durability after 1 use, so we changed the wands.yml config to our old setup, which will spam errors in console, also very anoying.

**Comment by UtechtDustin** [comment]
The plugin was my first plugin ever, so it has some bad issues..
In that case the plugin tries to figure out the wand with the name of the wand and the material.
So the plugin thinks the infinity wand is the first wand (because all wands have the same material and name).
As workaround rename the wand or use a other material, also you should change `durability.enabled` to false.

I'm working on a complete rewrite to develop a good version of this plugin without this kind of issues.
